import Foundation

/// Renders the `client_config.toml` and resolver file that the StormDNS Go
/// client consumes via `-config` and `-resolvers`. Field names and value
/// ranges follow client_config.toml.simple from the StormDNS repo.
enum ConfigRenderer {

    static func renderClientToml(
        server: ServerProfile,
        settings: AppSettings
    ) -> String {
        let s = settings
        func clamp(_ v: Int, _ lo: Int, _ hi: Int) -> Int { max(lo, min(hi, v)) }

        let dup = clamp(s.uploadDuplication, 1, 8)
        let dupDown = clamp(s.downloadDuplication, 1, 8)
        let dupUpSetup = clamp(s.uploadSetupDuplication, dup, 8)
        let dupDownSetup = clamp(s.downloadSetupDuplication, dupDown, 8)

        return """
        # Generated by WhiteDNS for macOS. Do not edit while connected.
        DOMAINS = ["\(esc(server.domain))"]
        DATA_ENCRYPTION_METHOD = \(server.encryptionMethod)
        ENCRYPTION_KEY = "\(esc(server.encryptionKey))"

        PROTOCOL_TYPE = "SOCKS5"
        LISTEN_IP = "\(esc(s.listenIp))"
        LISTEN_PORT = \(s.listenPort)
        SOCKS5_AUTH = false

        LOCAL_DNS_ENABLED = false

        RESOLVER_BALANCING_STRATEGY = \(clamp(s.resolverBalancingStrategy, 1, 4))

        UPLOAD_PACKET_DUPLICATION_COUNT = \(dup)
        DOWNLOAD_PACKET_DUPLICATION_COUNT = \(dupDown)
        UPLOAD_SETUP_PACKET_DUPLICATION_COUNT = \(dupUpSetup)
        DOWNLOAD_SETUP_PACKET_DUPLICATION_COUNT = \(dupDownSetup)

        UPLOAD_COMPRESSION_TYPE = \(clamp(s.uploadCompression, 0, 3))
        DOWNLOAD_COMPRESSION_TYPE = \(clamp(s.downloadCompression, 0, 3))

        MIN_UPLOAD_MTU = \(s.minUploadMtu)
        MAX_UPLOAD_MTU = \(max(s.minUploadMtu, s.maxUploadMtu))
        MIN_DOWNLOAD_MTU = \(s.minDownloadMtu)
        MAX_DOWNLOAD_MTU = \(max(s.minDownloadMtu, s.maxDownloadMtu))

        PING_WATCHDOG_TIMEOUT_SECONDS = \(s.pingWatchdogTimeoutSeconds)

        # Always start from the resolver file: avoids the interactive prompt.
        STARTUP_MODE = "resolvers"

        LOG_LEVEL = "\(esc(s.logLevel))"
        LOG_TO_FILE = false
        STATS_REPORT_INTERVAL_SECONDS = \(max(0, s.statsReportIntervalSeconds))

        CONFIG_VERSION = "1"
        """
    }

    static func renderResolvers(_ resolver: ResolverProfile) -> String {
        resolver.entries.joined(separator: "\n") + "\n"
    }

    /// Escapes a TOML basic-string value (backslash and double quote).
    private static func esc(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
